import matplotlib.pyplot as plt 
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.special import softmax
from sindy_utils import sindy_library_equations
import pickle
import os
def build_equations(coeff_matrix, resulting_library, coeff_thresh, active_terms):
    """
    Build equations based on coefficient matrix and library.

    This function constructs equations for each row of the coefficient matrix using the provided library and coefficient matrix.

    Arguments:
        coeff_matrix (numpy.ndarray): The coefficient matrix from the SINDy model.
        resulting_library (dict): The resulting library of equations generated by `sindy_library_equations`.
        coeff_thresh (float): The threshold below which coefficients are considered negligible.

    Returns:
        equations (list): A list of equations representing the relationships between variables.
    """
    latent_dim = coeff_matrix.shape[0]  # Number of latent dimensions

    # Check if the dimensions match
    if coeff_matrix.shape[1] != len(resulting_library):
        print('error: coeff_matrix.shape[1] != len(resulting_library)')

    equations = []
    active_variable={}
    # Iterate through each row of the coefficient matrix
    for row_index in range(0, latent_dim):
        equation_parts=[]
        active_variable[row_index] = set()
        for col_index, value in resulting_library.items():
            if np.abs(coeff_matrix[row_index][col_index]) > coeff_thresh:
                equation_parts.append(f"{coeff_matrix[row_index][col_index]:.5f}*{value}")
                active_variable[row_index].update(list(active_terms[col_index]))
        # Combine equation parts and create the equation
        equation = f"dz{row_index} = " + ' + '.join(equation_parts)
        equations.append(equation)
    return equations, active_variable


def generate_library_and_nature(params):
    """
    Generates the SINDy library and nature vector based on the parameters.

    Parameters:
    - params: Dictionary containing experiment parameters.

    Returns:
    - resulting_library: Library equations.
    - terms: List of terms.
    - tupple: Tuple containing the library information.
    - nature: List of nature signs for each term.
    """
    
    latent_dim = params['latent_dim']
    
    # Create variable library names
    variable_lib = [f'z{z}' for z in range(latent_dim)]

    # Build the SINDy library
    resulting_library, terms, tupple = sindy_library_equations(
        variable_lib, latent_dim, params['poly_order'],
        include_constant=True,
        include_sine=params['include_sine'],
        include_tan=params['include_tan'],
        include_log=params['include_log'],
        include_exp=params['include_exp'],
        include_reciprocal=params['include_reciprocal_func']
    )

    # Build the nature array
    nature = [0]  # Constant term
    nature.extend([1] * latent_dim)  # Linear terms

    # Include additional terms based on parameters
    if params['include_reciprocal_func']:
        nature.extend([-1] * latent_dim)
    if params['include_tan']:
        nature.extend([1] * latent_dim)
    if params['include_exp']:
        nature.extend([1] * latent_dim)
    nature.extend([1] * int(latent_dim * (latent_dim + 1) / 2))  # Quadratic terms
    if params['include_sine']:
        nature.extend([1] * latent_dim)

    return resulting_library, terms, tupple, nature


def evaluate_model_with_library(experiments, exp_number, params):
    """
    Evaluates the model by identifying misclassifications, building equations, and printing results.

    Parameters:
    - experiments: Object containing experiment data.
    - exp_number: Experiment index to evaluate.
    - params: Dictionary containing SINDy parameters.
    - build_equations: Function to generate the equations.

    Returns:
    - cross_index: List of misclassified indices.
    - active_terms: List of active terms in the model.
    - equations: List of generated equations.
    """
    
    print(f"\nEvaluating Experiment {exp_number}")
    
    # Generate the library and nature array
    resulting_library, terms, _, nature = generate_library_and_nature(params)

    # Identify misclassifications
    cross_index = []
    count = 0

    for i in range(len(experiments.experiments[exp_number].model['class_score'])):
        pred = np.argmax(softmax(experiments.experiments[exp_number].model['class_score'][i]))
        true = np.argmax(experiments.experiments[exp_number].model['class_labels'][i])
        
        if pred != true:
            cross_index.append(i)
            count += 1

    print(f"Misclassified samples: {count}")

    # Retrieve the coefficient matrix and build the equations
    common = (experiments.experiments[exp_number].model['coefficient_mask'] * 
              experiments.experiments[exp_number].model['sindy_coefficients']).T

    equations, active_terms = build_equations(common, resulting_library, 0, terms)

    # Apply sign correction based on nature matrix
    nature_all = [nature] * params['latent_dim']
    signum_array = np.sign(common) * nature_all

    # Display the results
    print("\nActive Terms:\n LHS terms :RHS terms")
    print(active_terms)
    
    for i, equation in enumerate(equations):
        print(f"\nEquation {i}: {equation}")

    return cross_index, active_terms, equations

def evaluate_model(experiments, exp_number, resulting_library, terms, params, nature):
    """
    Evaluates the model by identifying misclassifications, building equations, and printing results.

    Parameters:
    - experiments: Object containing experiment data.
    - exp_number: Experiment index to evaluate.
    - resulting_library: Library used to build equations.
    - terms: List of terms for building equations.
    - params: Dictionary containing 'latent_dim'.
    - nature: Nature matrix used for sign alignment.

    Returns:
    - cross_index: List of misclassified indices.
    - active_terms: List of active terms in the model.
    - equations: List of generated equations.
    """
    
    print(f"Evaluating Experiment {exp_number}")
    
    # Identify misclassifications
    cross_index = []
    count = 0

    for i in range(len(experiments.experiments[exp_number].model['class_score'])):
        pred = np.argmax(softmax(experiments.experiments[exp_number].model['class_score'][i]))
        true = np.argmax(experiments.experiments[exp_number].model['class_labels'][i])
        
        if pred != true:
            cross_index.append(i)
            count += 1

    print(f"Misclassified samples: {count}")

    # Retrieve the coefficient matrix and build the equations
    common = (experiments.experiments[exp_number].model['coefficient_mask'] * 
              experiments.experiments[exp_number].model['sindy_coefficients']).T

    equations, active_terms = build_equations(common, resulting_library, 0, terms)

    # Apply sign correction based on nature matrix
    nature_all = [nature] * params['latent_dim']
    signum_array = np.sign(common) * nature_all

    # Display the results
    print("\nActive Terms:")
    print(active_terms)
    
    for i, equation in enumerate(equations):
        print(f"\nEquation {i}: {equation}")

    return cross_index, active_terms, equations


def evaluate_classification_results(experiments, exp_num, index_to_clusters, save_path='confusion_matrix.pdf'):
    """
    Evaluates an experiment by generating the confusion matrix, accuracy, and classification report.
    
    Parameters:
    - experiments: The object containing the experiment data.
    - exp_num: The experiment number to evaluate.
    - index_to_clusters: A dictionary mapping numerical labels to string labels.
    - save_path: Path to save the confusion matrix plot (default: 'confusion_matrix.pdf').

    Returns:
    - accuracy: Accuracy score of the model.
    - class_report: Classification report as a string.
    - conf_matrix: The confusion matrix as a NumPy array.
    """
    
    # Initialize lists to store the true and predicted classes
    true_classes = []
    pred_classes = []
    
    # Iterate over each item in the experiment's model
    for i in range(len(experiments.experiments[exp_num].model['class_score'])):
        # Calculate the predicted class using softmax and argmax
        predicted_class = np.argmax(softmax(experiments.experiments[exp_num].model['class_score'][i]))
        # Get the actual class label
        true_class = np.argmax(experiments.experiments[exp_num].model['class_labels'][i])
        
        # Append the true and predicted classes to their respective lists
        true_classes.append(true_class)
        pred_classes.append(predicted_class)

    # Convert numerical labels to string labels
    true_classes_str = [index_to_clusters[cls] for cls in true_classes]
    pred_classes_str = [index_to_clusters[cls] for cls in pred_classes]

    # Print the experiment number
    print(f"Experiment Number: {exp_num}")

    # Generate the confusion matrix
    conf_matrix = confusion_matrix(true_classes_str, pred_classes_str, labels=list(index_to_clusters.values()))

    # Print the confusion matrix
    print("\nConfusion Matrix:")
    print(conf_matrix)

    # Calculate accuracy and classification report
    accuracy = accuracy_score(true_classes_str, pred_classes_str)
    class_report = classification_report(true_classes_str, pred_classes_str)

    print("\nClassification Report:")
    print(class_report)
    print(f"Accuracy: {accuracy:.4f}")

    # Visualize the confusion matrix
    plt.figure(figsize=(10, 7))
    sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues",
                xticklabels=list(index_to_clusters.values()),
                yticklabels=list(index_to_clusters.values()))
    plt.xlabel('Predicted Cell Type')
    plt.ylabel('True Cell Type')
    plt.title('Confusion Matrix')
    plt.savefig(save_path, format='pdf', bbox_inches='tight')
    plt.show()

    return accuracy, class_report, conf_matrix

def plot_loss_curves(train_loss, val_loss):
    loss_categories = 7  
    plot_names = [
        '(a) Combined Loss', '(b) Reconstruction Loss', '(c) SINDy_x Loss',
        '(d) SINDy_z Loss', '(e) SINDy Norm', '(f) Autoencoder Norm', '(g) Classification Error'
    ]
    
    epochs = len(train_loss)
    x_values = np.arange(epochs) * 50  

    for i in range(loss_categories):
        # Skip 'Autoencoder Norm'
        if plot_names[i] == '(f) Autoencoder Norm':
            continue  

        plt.figure(figsize=(8, 6))
        plt.plot(x_values, train_loss[:, i], label='Training Loss')
        plt.plot(x_values, val_loss[:, i], label='Validation Loss', linestyle='--')
        plt.xlabel('Epochs')
        plt.ylabel('Loss (log scale)')
        plt.title(plot_names[i])
        plt.yscale('log')
        plt.legend()
        plt.grid(True)
        
        plt.tight_layout()
        # Uncomment the line below to save the figures
        # plt.savefig(f"{plot_names[i].replace(' ', '_')}_Loss_Curve.pdf", format='pdf', bbox_inches='tight')
        plt.show()

def extract_and_save_weights(experiment, model_type, num_layers, save_path):
    """
    Extracts and saves weights and biases for a given model type.

    Args:
        experiment (object): The experiment containing the model.
        model_type (str): The type of model ('decoder' or 'classifier').
        num_layers (int): Number of layers to extract.
        save_path (str): Path to save the extracted weights.
    """
    weights = {}
    biases = {}

    for layer in range(num_layers + 1):
        weights[layer] = experiment.model[f'{model_type}_weights'][layer]
        biases[layer] = experiment.model[f'{model_type}_biases'][layer]

    weights_list = [weights[layer] for layer in range(num_layers + 1)]
    biases_list = [biases[layer] for layer in range(num_layers + 1)]

    # Save the extracted weights and biases
    with open(os.path.join(save_path, f'{model_type}_weights_list.pkl'), 'wb') as f:
        pickle.dump(weights_list, f)

    with open(os.path.join(save_path, f'{model_type}_biases_list.pkl'), 'wb') as f:
        pickle.dump(biases_list, f)