model_config:
  latent_dim: 6
  num_classes: 9
  ae_widths: [512, 32]
  classifier_widths: [8]

sindy_config:
  model_order: 1
  poly_order: 2
  include_sine: true
  include_exp: true
  include_reciprocal_func: true

loss_weights:
  recon_wt: 10.0
  sindy_wt_z: 5.0
  sindy_wt_x: 0.1
  class_wt: 1.0
  l1_reg: 1.0

train_settings:
  optimizer: "adam"
  lr: 0.001
  num_epochs: 1000
  refinement_epochs: 500
  batch_size: 1024
  threshold_frequency: 200
  coefficient_threshold: 0.1
  sequential_thresholding: true

training_config:
  print_progress: true
  print_frequency: 50
  plot_loss: true
  experiments_dir: "experiments"
  experiment_name: "sergio_test_01"
  save_model_path: "model.pt"
